version: "3"

services: 
    web-server:
        image: "node:14.7.0-buster"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=development
        volumes:
            - .:/home/node/app
        ports:
            - 1000:3000
        command: "npm start"